package main

import (
	"fmt"
	"httper/internal/echo/handler"
	"net/http"
	"os"
	"path"
	"time"
)

const address = ":8080"

func main() {
	mux := handler.NewMux()

	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	fmt.Println("Listening on", address)

	// Certs live under echo/certs (generated by `make mkcert`); the server is
	// expected to run from the repo root via `go run ./cmd/echo`.
	certFile := path.Join(wd, "echo/certs/localhost+2.pem")
	keyFile := path.Join(wd, "echo/certs/localhost+2-key.pem")

	server := &http.Server{
		Handler:           mux,
		Addr:              address,
		ReadHeaderTimeout: 3 * time.Second,
	}

	if err = server.ListenAndServeTLS(
		certFile,
		keyFile,
	); err != nil {
		panic(err)
	}
}
