// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcecho

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoServiceClient interface {
	// Echo returns the message plus the incoming request metadata, and sets a
	// response header and trailer so metadata assertions are possible.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Fail returns the gRPC status code given in the request.
	Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Countdown streams count messages from count down to 1.
	Countdown(ctx context.Context, in *CountdownRequest, opts ...grpc.CallOption) (EchoService_CountdownClient, error)
	// Collect exists only to exercise client-streaming rejection.
	Collect(ctx context.Context, opts ...grpc.CallOption) (EchoService_CollectClient, error)
}

type echoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoServiceClient(cc grpc.ClientConnInterface) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/grpcecho.EchoService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) Fail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/grpcecho.EchoService/Fail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) Countdown(ctx context.Context, in *CountdownRequest, opts ...grpc.CallOption) (EchoService_CountdownClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EchoService_serviceDesc.Streams[0], "/grpcecho.EchoService/Countdown", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoServiceCountdownClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EchoService_CountdownClient interface {
	Recv() (*CountdownResponse, error)
	grpc.ClientStream
}

type echoServiceCountdownClient struct {
	grpc.ClientStream
}

func (x *echoServiceCountdownClient) Recv() (*CountdownResponse, error) {
	m := new(CountdownResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *echoServiceClient) Collect(ctx context.Context, opts ...grpc.CallOption) (EchoService_CollectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EchoService_serviceDesc.Streams[1], "/grpcecho.EchoService/Collect", opts...)
	if err != nil {
		return nil, err
	}
	x := &echoServiceCollectClient{stream}
	return x, nil
}

type EchoService_CollectClient interface {
	Send(*EchoRequest) error
	CloseAndRecv() (*EchoResponse, error)
	grpc.ClientStream
}

type echoServiceCollectClient struct {
	grpc.ClientStream
}

func (x *echoServiceCollectClient) Send(m *EchoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *echoServiceCollectClient) CloseAndRecv() (*EchoResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EchoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EchoServiceServer is the server API for EchoService service.
// All implementations must embed UnimplementedEchoServiceServer
// for forward compatibility
type EchoServiceServer interface {
	// Echo returns the message plus the incoming request metadata, and sets a
	// response header and trailer so metadata assertions are possible.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// Fail returns the gRPC status code given in the request.
	Fail(context.Context, *FailRequest) (*EchoResponse, error)
	// Countdown streams count messages from count down to 1.
	Countdown(*CountdownRequest, EchoService_CountdownServer) error
	// Collect exists only to exercise client-streaming rejection.
	Collect(EchoService_CollectServer) error
	mustEmbedUnimplementedEchoServiceServer()
}

// UnimplementedEchoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEchoServiceServer struct {
}

func (*UnimplementedEchoServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedEchoServiceServer) Fail(context.Context, *FailRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fail not implemented")
}
func (*UnimplementedEchoServiceServer) Countdown(*CountdownRequest, EchoService_CountdownServer) error {
	return status.Errorf(codes.Unimplemented, "method Countdown not implemented")
}
func (*UnimplementedEchoServiceServer) Collect(EchoService_CollectServer) error {
	return status.Errorf(codes.Unimplemented, "method Collect not implemented")
}
func (*UnimplementedEchoServiceServer) mustEmbedUnimplementedEchoServiceServer() {}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcecho.EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcecho.EchoService/Fail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Fail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_Countdown_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CountdownRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServiceServer).Countdown(m, &echoServiceCountdownServer{stream})
}

type EchoService_CountdownServer interface {
	Send(*CountdownResponse) error
	grpc.ServerStream
}

type echoServiceCountdownServer struct {
	grpc.ServerStream
}

func (x *echoServiceCountdownServer) Send(m *CountdownResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EchoService_Collect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServiceServer).Collect(&echoServiceCollectServer{stream})
}

type EchoService_CollectServer interface {
	SendAndClose(*EchoResponse) error
	Recv() (*EchoRequest, error)
	grpc.ServerStream
}

type echoServiceCollectServer struct {
	grpc.ServerStream
}

func (x *echoServiceCollectServer) SendAndClose(m *EchoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *echoServiceCollectServer) Recv() (*EchoRequest, error) {
	m := new(EchoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcecho.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _EchoService_Fail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Countdown",
			Handler:       _EchoService_Countdown_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Collect",
			Handler:       _EchoService_Collect_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "echo.proto",
}
